###---------------------------FILM--------------------------###

### 19. Listar todas las películas
GET http://localhost:3000/film
Content-Type: application/json

### 20. Mostrar información de una película
GET http://localhost:3000/films/1002
Content-Type: application/json

### 21. Listar todas las películas por titulo
GET http://localhost:3000/film/dear
Content-Type: application/json

### 22. Agregar película
POST http://localhost:3000/film
Content-Type: application/json

{
    "title":"Dear Evan Hansen",
    "description":"Evan Hansen is a high school senior with social anxiety disorder. He embarks on a journey of self-discovery and acceptance following the suicide of a classmate",
    "release_year": 2021 ,
    "language_id": 1,
    "rental_duration": 3,
    "rental_rate": 4.99,
    "length_":132,
    "replacement_post":19.99,
    "rating":"PG-13",
    "special_features":"Deleted Scenes"
}

### 23. Mostrar películas por el rating
GET http://localhost:3000/films/rate/1
Content-Type: application/json
